# questions.toml

[[questions]]
question = "Столица Норвегии"
answers = ["Осло"]
alternatives = ["Белград", "Хельсинки", "Портсмут"]

[[questions]]
question = "В какой стране находится город Мариенхамн"
answers = ["Финляндия"]
alternatives = ["Чехия", "Исландия", "Литва"]

[[questions]]
question = "Какая из этих стран НЕ находится в Африке"
answers = ["Иордания"]
alternatives = ["Кения", "Египет", "Мали"]

[[questions]]
question = "В какой стране находится город Вентспилс"
answers = ["Латвия"]
alternatives = ["Португалия", "США", "Эстония"]

[[questions]]
question = "Столица ЮАР"
answers = ["Претория"]
alternatives = ["Кейптаун", "Йоханнесбург", "Блумфонтейн"]


[[questions]]
question = "Какой из этих городов находится НЕ в Европе"
answers = ["Хомс"]
alternatives = ["Кёльн", "Линц", "Вроцлав"]

[[questions]]
question = "Какие флаги имеют в своей раскраске синий цвет"
answers = ["Швеция/Эсватини/Греция"]
alternatives = [
    ["Греция/Перу/Мадагаскар"],
    ["Швеция/Новая Зеландия/Египет"],
    ["Барбадос/Финляндия/Киргизия"],
]

[[questions]]
question = "Какие города находятся во Франции"
answers = ["Марсель", "Монпелье"]
alternatives = ["Линц", "Эфле"]

